WebSocketAddress: ws://127.0.0.1:8080/llbds
# NoneBot2 的 WebSocket 地址, 由 NoneBot2 机器人目录下 .env 文件中的 HOST 和 PORT 决定

HttpHost: 127.0.0.1
# LLBDS 的 HTTP API 地址

HttpPost: 8081
# LLBDS 的 HTTP API 端口

Token: your_token
# 鉴权 Token, 由 NoneBot2 机器人目录下 .env 文件中的 LLBDS_TOKEN 决定

ReconnectInterval: 5
# WebSocket 重连间隔, 单位为秒, 默认为 5 秒

HeartbeatInterval: 5
# 心跳间隔, 单位为秒, 默认为 5 秒

Timeout: 60
# 缓存对象的超时时间, 单位为秒, 默认为 60 秒

ForwardEvents:
  # 需要转发的事件列表, 参阅 https://docs.litebds.com/zh-Hans/#/LLSEPluginDevelopment/EventAPI/Listen 及相关内容
  - PreJoin
  - Join
  - Left
  - Respawn
  - PlayerDie
  - Chat
  - ChangeDim
